package dev.omnitalk.rag

import android.content.Context
import android.util.Log
import org.json.JSONArray
import org.json.JSONObject
import java.io.File

/**
 * Decks on disk.
 *
 * Without this the library lived only in memory: closing the app, or Android
 * reclaiming it in the background, threw away every imported PDF and the reader
 * had to find and re-import the file. A study tool that forgets your notes
 * between sessions is not a study tool.
 *
 * The extracted text is stored, not the original PDF. Extraction is the slow
 * part (seconds for a large deck) and the source file may live behind a URI
 * permission that does not survive a reboot.
 */
class DocStore(ctx: Context) {

    private val dir = File(ctx.filesDir, "decks").apply { mkdirs() }

    private fun fileFor(doc: Document) = File(dir, doc.id.hashCode().toString() + ".json")

    /**
     * Read-modify-write a deck's record.
     *
     * Every writer used to rebuild the whole object and hand-copy the fields it
     * did not own — the topics list survived a re-save only because one call site
     * remembered to read it back first. That is a bug waiting for the second
     * field, and cards and progress are the second and third. Merging into what
     * is already on disk means a writer only has to know about its own key.
     */
    private fun update(doc: Document, mutate: (JSONObject) -> Unit) {
        runCatching {
            val f = fileFor(doc)
            val o = if (f.exists())
                runCatching { JSONObject(f.readText()) }.getOrDefault(JSONObject())
            else JSONObject()
            o.put("id", doc.id).put("title", doc.title).put("charCount", doc.charCount)
            mutate(o)
            f.writeText(o.toString())
        }.onFailure { Log.e(TAG, "save failed", it) }
    }

    private fun read(doc: Document): JSONObject? {
        val f = fileFor(doc)
        if (!f.exists()) return null
        return runCatching { JSONObject(f.readText()) }.getOrNull()
    }

    fun save(doc: Document, pages: List<String>, topics: List<Topic>? = null) {
        update(doc) { o ->
            o.put("pages", JSONArray(pages))
            if (topics != null) o.put("topics", JSONArray(topics.map { t ->
                JSONObject()
                    .put("title", t.title).put("from", t.fromPage).put("to", t.toPage)
                    .put("chunks", JSONArray(t.chunkIds))
            }))
        }
    }

    /**
     * The cards made for this deck, and how practice went.
     *
     * Cards cost about ninety seconds of the phone's time to generate. Keeping
     * them only in memory meant switching decks — or Android reclaiming the app
     * while the reader looked something up — silently destroyed the most
     * expensive thing the app produces. Cramming happens in interrupted sessions;
     * work that does not survive an interruption is work the reader will not do
     * twice.
     */
    fun saveStudy(doc: Document, s: StudyState) {
        update(doc) { o ->
            o.put("cardsScope", s.cardsScope)
            o.put("cards", JSONArray(s.cards.map {
                JSONObject().put("q", it.front).put("a", it.back).put("p", it.page)
            }))
            o.put("known", JSONArray(s.known.toList()))
            o.put("askedPages", JSONArray(s.askedPages.toList()))
            o.put("cardedPages", JSONArray(s.cardedPages.toList()))
        }
    }

    fun loadStudy(doc: Document): StudyState {
        val o = read(doc) ?: return StudyState()
        fun ints(key: String): Set<Int> {
            val a = o.optJSONArray(key) ?: return emptySet()
            return (0 until a.length()).map { a.getInt(it) }.toSet()
        }
        val arr = o.optJSONArray("cards")
        val cards = if (arr == null) emptyList() else (0 until arr.length()).map { i ->
            val c = arr.getJSONObject(i)
            Card(c.getString("q"), c.getString("a"), c.optInt("p", 1))
        }
        return StudyState(
            cards = cards,
            cardsScope = o.optString("cardsScope", ""),
            known = ints("known"),
            askedPages = ints("askedPages"),
            cardedPages = ints("cardedPages")
        )
    }

    /** Topics generated by the model for this deck, if the pass has been run. */
    fun loadTopics(doc: Document): List<Topic> {
        val o = read(doc) ?: return emptyList()
        return runCatching {
            val arr = o.optJSONArray("topics") ?: return emptyList()
            (0 until arr.length()).map { i ->
                val t = arr.getJSONObject(i)
                val ids = t.getJSONArray("chunks")
                Topic(
                    t.getString("title"), t.getInt("from"), t.getInt("to"),
                    (0 until ids.length()).map { ids.getInt(it) }
                )
            }
        }.getOrDefault(emptyList())
    }

    /** @return decks with their page text, newest file first. */
    fun loadAll(): List<Pair<Document, List<String>>> {
        val files = dir.listFiles { f -> f.extension == "json" } ?: return emptyList()
        return files.sortedByDescending { it.lastModified() }.mapNotNull { f ->
            runCatching {
                val o = JSONObject(f.readText())
                val arr = o.getJSONArray("pages")
                val pages = (0 until arr.length()).map { arr.getString(it) }
                val chunks = Chunker.chunk(pages)
                Document(
                    id = o.getString("id"),
                    title = o.getString("title"),
                    pageCount = pages.size,
                    chunks = chunks,
                    charCount = o.optInt("charCount", pages.sumOf { it.length })
                ) to pages
            }.getOrNull()
        }
    }

    fun delete(doc: Document) {
        runCatching { fileFor(doc).delete() }
    }

    private companion object { const val TAG = "otstore" }
}
