package dev.omnitalk.rag

import android.content.Context
import android.util.Log
import org.json.JSONArray
import org.json.JSONObject
import java.io.File

/**
 * Decks on disk.
 *
 * Without this the library lived only in memory: closing the app, or Android
 * reclaiming it in the background, threw away every imported PDF and the reader
 * had to find and re-import the file. A study tool that forgets your notes
 * between sessions is not a study tool.
 *
 * The extracted text is stored, not the original PDF. Extraction is the slow
 * part (seconds for a large deck) and the source file may live behind a URI
 * permission that does not survive a reboot.
 */
class DocStore(ctx: Context) {

    private val dir = File(ctx.filesDir, "decks").apply { mkdirs() }

    fun save(doc: Document, pages: List<String>, topics: List<Topic>? = null) {
        runCatching {
            val f = File(dir, doc.id.hashCode().toString() + ".json")
            // Keep any topics already generated for this deck unless replacing them.
            val existing = if (topics == null && f.exists())
                runCatching { JSONObject(f.readText()).optJSONArray("topics") }.getOrNull()
            else null
            val o = JSONObject()
                .put("id", doc.id)
                .put("title", doc.title)
                .put("charCount", doc.charCount)
                .put("pages", JSONArray(pages))
            when {
                topics != null -> o.put("topics", JSONArray(topics.map { t ->
                    JSONObject()
                        .put("title", t.title).put("from", t.fromPage).put("to", t.toPage)
                        .put("chunks", JSONArray(t.chunkIds))
                }))
                existing != null -> o.put("topics", existing)
            }
            f.writeText(o.toString())
        }.onFailure { Log.e(TAG, "save failed", it) }
    }

    /** Topics generated by the model for this deck, if the pass has been run. */
    fun loadTopics(doc: Document): List<Topic> {
        val f = File(dir, doc.id.hashCode().toString() + ".json")
        if (!f.exists()) return emptyList()
        return runCatching {
            val arr = JSONObject(f.readText()).optJSONArray("topics") ?: return emptyList()
            (0 until arr.length()).map { i ->
                val t = arr.getJSONObject(i)
                val ids = t.getJSONArray("chunks")
                Topic(
                    t.getString("title"), t.getInt("from"), t.getInt("to"),
                    (0 until ids.length()).map { ids.getInt(it) }
                )
            }
        }.getOrDefault(emptyList())
    }

    /** @return decks with their page text, newest file first. */
    fun loadAll(): List<Pair<Document, List<String>>> {
        val files = dir.listFiles { f -> f.extension == "json" } ?: return emptyList()
        return files.sortedByDescending { it.lastModified() }.mapNotNull { f ->
            runCatching {
                val o = JSONObject(f.readText())
                val arr = o.getJSONArray("pages")
                val pages = (0 until arr.length()).map { arr.getString(it) }
                val chunks = Chunker.chunk(pages)
                Document(
                    id = o.getString("id"),
                    title = o.getString("title"),
                    pageCount = pages.size,
                    chunks = chunks,
                    charCount = o.optInt("charCount", pages.sumOf { it.length })
                ) to pages
            }.getOrNull()
        }
    }

    fun delete(doc: Document) {
        runCatching { File(dir, doc.id.hashCode().toString() + ".json").delete() }
    }

    private companion object { const val TAG = "otstore" }
}
